#!/bin/bash
#set -e;

APP=$2

HOME="$DOKKU_ROOT/.postgresql"

check_exists() {
  if [[ ! -d "$DOKKU_ROOT/$APP" ]]; then
    echo "App must exist before creating postgresql storage for it"
    exit 1
  fi
}

check_app() {
  if [[ -z "$APP" ]]; then
    echo "You must specify an app name"
    exit 1
  fi
}

admin_pass=$(cat "$DOKKU_ROOT/.postgresql/admin_pw")
postgresql_database="${APP}_production"


postgresql_public_ip="localhost"
postgresql_private_ip="$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}')"
postgresql_port=5432

case "$1" in
  postgresql:admin_console)

    PGPASSWORD=$(cat "$DOKKU_ROOT/.postgresql/admin_pw") PGUSER=root psql -p "$postgresql_port" -h localhost postgres
    ;;
  postgresql:console)
    check_app
    check_exists

    PGPASSWORD=$(cat "$DOKKU_ROOT/.postgresql/pass_$APP") PGUSER="$APP" psql -p "$postgresql_port" -h localhost "$postgresql_database"
    ;;
  postgresql:create)
    check_app
    check_exists

    postgresql_password=$(openssl rand -base64 32|base64)
    echo $postgresql_password > "$DOKKU_ROOT/.postgresql/pass_$APP"

    admin_pw=$(cat "$DOKKU_ROOT/.postgresql/admin_pw")
    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "CREATE USER \"${APP}\" WITH PASSWORD '${postgresql_password}';"
    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "CREATE DATABASE \"${postgresql_database}\";"
    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "GRANT ALL PRIVILEGES ON DATABASE \"${postgresql_database}\" to \"${APP}\";"

    dokku config:set "$APP" DATABASE_URL="postgres://${APP}:${postgresql_password}@${postgresql_private_ip}:${postgresql_port}/${postgresql_database}"
    ;;
  postgresql:delete)
    check_app
    check_exists

    admin_pw=$(cat "$DOKKU_ROOT/.postgresql/admin_pw")
    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "DROP DATABASE \"${postgresql_database}\";"
    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "DROP USER \"${APP}\";"

    dokku config:unset "$APP" DATABASE_URL
    ;;
  postgresql:list)

    admin_pw=$(cat "$DOKKU_ROOT/.postgresql/admin_pw")
    PGPASSWORD="$admin_pw" PGUSER=root psql -h "$postgresql_public_ip" -p "$postgresql_port" -w template1 <<< "\list"
    ;;
  help)
    cat && cat<<EOF
    postgresql:admin_console Launch a postgresql console as admin user
    postgresql:console <app> Launch a postgresql console for a given app
    postgresql:create <app>  Create a Postgresql database
    postgresql:delete <app>  Delete specified Postgresql database
    postgresql:list          List all databases
EOF
    ;;
esac
