#!/bin/bash

apt-get -y install postgresql-client-9.3

if [[ ! -d "$DOKKU_ROOT/.postgresql" ]]; then
  mkdir -p "$DOKKU_ROOT/.postgresql"
  
  if [[ ! -f "$DOKKU_ROOT/.postgresql/admin_pw" ]]; then
    admin_pass=$(openssl rand -base64 32|base64)
    echo $admin_pass > "$DOKKU_ROOT/.postgresql/admin_pw"

    chown dokku: "$DOKKU_ROOT/.postgresql"
    chown dokku: "$DOKKU_ROOT/.postgresql/admin_pw"
  fi
fi
